{% set version = "6.0.6" %}

package:
  name: devpi-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/devpi-client/devpi-client-{{ version }}.tar.gz
  sha256: 313bccbf2dd6a55f9b6dbfecb06b23528bf213f3a3b78056cfb230805fe41098

build:
  entry_points:
    - devpi = devpi.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - iniconfig
    - python >=3.7
    - python-build
    - check-manifest >=0.28
    - devpi-common <4,>=3.6.0
    - pep517
    - pkginfo >=1.4.2
    - platformdirs
    - pluggy >=0.6.0,<2.0
    - py >=1.4.31

test:
  imports:
    - devpi
  commands:
    - pip check
    - devpi --help
  requires:
    - pip

about:
  home: https://devpi.net
  summary: devpi upload/install/... workflow commands for Python developers
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/devpi/devpi

extra:
  recipe-maintainers:
    - bollwyvl
