{% set version = "7.0.0" %}

package:
  name: devpi-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/devpi-client/devpi-client-{{ version }}.tar.gz
  sha256: 008fc636e6dbefe9f0cffbcceaffc9a14b56ba9eab04989e297b45433add3e41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - devpi = devpi.main:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - check-manifest >=0.28
    - colorama
    - devpi-common <5,>=4
    - iniconfig
    - pkginfo >=1.4.2
    - platformdirs
    - pluggy >=0.6.0,<2.0
    - python >=3.7
    - python-build

test:
  imports:
    - devpi
  commands:
    - pip check
    - devpi --help
  requires:
    - pip

about:
  home: https://devpi.net
  summary: devpi upload/install/... workflow commands for Python developers
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/devpi/devpi

extra:
  recipe-maintainers:
    - bollwyvl
